import json
import os
import re
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from abc import ABC, abstractmethod
from typing import Any, Dict

from prompts.cover_letter import (
    COVER_LETTER_SYSTEM_PROMPT,
    build_cover_letter_user_prompt,
)
from services.bedrock import bedrock_client


class CoverLetterProvider(ABC):
    name: str

    @abstractmethod
    def generate_cover_letter(
        self,
        cv_content: str,
        job_description: str,
        company_name: str | None = None,
        instructions: str | None = None,
    ) -> Dict[str, Any]:
        raise NotImplementedError


class MockCoverLetterProvider(CoverLetterProvider):
    name = "mock"

    def generate_cover_letter(
        self,
        cv_content: str,
        job_description: str,
        company_name: str | None = None,
        instructions: str | None = None,
    ) -> Dict[str, Any]:
        cv_lines = [
            line.strip(" -*\t")
            for line in cv_content.splitlines()
            if line.strip() and not line.strip().startswith("%")
        ]
        jd_lines = [
            line.strip(" -*\t")
            for line in job_description.splitlines()
            if line.strip()
        ]

        evidence = self._pick_evidence(cv_lines)
        matches = self._pick_matches(jd_lines)
        weaker_points = self._pick_weaker_points(jd_lines, cv_content)

        opening_company = company_name or "your team"
        cover_letter = (
            f"Dear Hiring Team,\n\n"
            f"I am writing to express my interest in the role at {opening_company}. "
            f"My background shows a consistent pattern of delivering practical results, "
            f"working across technical and business needs, and adapting quickly to new challenges.\n\n"
            f"What stands out most in my experience is {evidence[0].lower()} "
            f"I also bring experience in {evidence[1].lower()} and {evidence[2].lower()} "
            f"which aligns well with the priorities described in the job posting, especially around "
            f"{matches[0].lower()} and {matches[1].lower()}.\n\n"
            f"I would be excited to bring this mix of execution, communication, and role-relevant experience "
            f"to your team. I am particularly motivated by the opportunity to contribute in a way that is "
            f"tailored to the needs of this role rather than relying on a one-size-fits-all profile.\n\n"
            f"Thank you for your time and consideration. I would welcome the opportunity to discuss how my "
            f"background can support your goals.\n"
        )

        if instructions:
            tone_note = f"Additional instruction considered: {instructions.strip()}"
        else:
            tone_note = "No extra user instruction was provided."

        return {
            "cover_letter": cover_letter,
            "key_matches": matches,
            "missing_or_weaker_points": weaker_points,
            "tone_notes": [
                "Generated by mock provider for local development.",
                tone_note,
            ],
        }

    def _pick_evidence(self, cv_lines: list[str]) -> list[str]:
        if not cv_lines:
            return [
                "relevant professional experience",
                "collaboration across teams",
                "delivery in technical environments",
            ]
        ranked = sorted(cv_lines, key=len, reverse=True)
        padded = ranked[:3]
        while len(padded) < 3:
            padded.append("relevant professional experience")
        return padded

    def _pick_matches(self, jd_lines: list[str]) -> list[str]:
        if not jd_lines:
            return [
                "delivering strong execution",
                "communicating clearly with stakeholders",
                "adapting to role requirements",
            ]
        cleaned = [self._normalize_requirement(line) for line in jd_lines[:5]]
        while len(cleaned) < 3:
            cleaned.append("cross-functional execution")
        return cleaned[:3]

    def _pick_weaker_points(self, jd_lines: list[str], cv_content: str) -> list[str]:
        weaker: list[str] = []
        lowered_cv = cv_content.lower()
        for line in jd_lines:
            normalized = self._normalize_requirement(line)
            tokens = [token for token in re.split(r"[^a-zA-Z0-9]+", normalized.lower()) if len(token) > 3]
            if tokens and not any(token in lowered_cv for token in tokens[:3]):
                weaker.append(normalized)
            if len(weaker) == 2:
                break
        if not weaker:
            weaker.append("Some role-specific details may need further tailoring.")
        return weaker

    def _normalize_requirement(self, value: str) -> str:
        value = re.sub(r"\s+", " ", value).strip(" -:\t")
        return value or "general role fit"


class BedrockCoverLetterProvider(CoverLetterProvider):
    name = "bedrock"

    def generate_cover_letter(
        self,
        cv_content: str,
        job_description: str,
        company_name: str | None = None,
        instructions: str | None = None,
    ) -> Dict[str, Any]:
        user_prompt = build_cover_letter_user_prompt(
            cv_content=cv_content,
            job_description=job_description,
            company_name=company_name,
            instructions=instructions,
        )
        response = bedrock_client.chat(
            messages=[{"role": "user", "content": user_prompt}],
            system_prompt=COVER_LETTER_SYSTEM_PROMPT,
            stream=False,
        )
        return self._parse_response(response)

    def _parse_response(self, response: str) -> Dict[str, Any]:
        response_text = response.strip()
        if "```json" in response_text:
            response_text = response_text.split("```json", 1)[1].split("```", 1)[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```", 1)[1].split("```", 1)[0].strip()

        data = json.loads(response_text)
        return {
            "cover_letter": data.get("cover_letter", "").strip(),
            "key_matches": data.get("key_matches", []),
            "missing_or_weaker_points": data.get("missing_or_weaker_points", []),
            "tone_notes": data.get("tone_notes", []),
        }


class GeminiCoverLetterProvider(CoverLetterProvider):
    name = "gemini"

    def __init__(self):
        self.api_key = (
            os.getenv("GEMINI_API_KEY")
            or os.getenv("GOOGLE_API_KEY")
            or ""
        ).strip()
        self.model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash").strip()

    def generate_cover_letter(
        self,
        cv_content: str,
        job_description: str,
        company_name: str | None = None,
        instructions: str | None = None,
    ) -> Dict[str, Any]:
        if not self.api_key:
            raise RuntimeError(
                "Gemini provider selected but GEMINI_API_KEY is not set."
            )

        user_prompt = build_cover_letter_user_prompt(
            cv_content=cv_content,
            job_description=job_description,
            company_name=company_name,
            instructions=instructions,
        )

        body = {
            "systemInstruction": {
                "parts": [{"text": COVER_LETTER_SYSTEM_PROMPT}]
            },
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": user_prompt}],
                }
            ],
            "generationConfig": {
                "temperature": 0.7,
                "responseMimeType": "application/json",
            },
        }

        endpoint = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{self.model}:generateContent"
        )
        request = Request(
            endpoint,
            data=json.dumps(body).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "x-goog-api-key": self.api_key,
            },
            method="POST",
        )

        try:
            with urlopen(request, timeout=60) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"Gemini HTTP error {exc.code}: {detail}") from exc
        except URLError as exc:
            raise RuntimeError(f"Gemini request failed: {exc.reason}") from exc

        return self._parse_response(payload)

    def _parse_response(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        candidates = payload.get("candidates") or []
        if not candidates:
            raise RuntimeError("Gemini returned no candidates.")

        parts = candidates[0].get("content", {}).get("parts", [])
        text = "".join(part.get("text", "") for part in parts if part.get("text"))
        if not text.strip():
            raise RuntimeError("Gemini returned an empty response.")

        response_text = text.strip()
        if "```json" in response_text:
            response_text = response_text.split("```json", 1)[1].split("```", 1)[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```", 1)[1].split("```", 1)[0].strip()

        data = json.loads(response_text)
        return {
            "cover_letter": data.get("cover_letter", "").strip(),
            "key_matches": data.get("key_matches", []),
            "missing_or_weaker_points": data.get("missing_or_weaker_points", []),
            "tone_notes": data.get("tone_notes", []),
        }


def get_cover_letter_provider() -> CoverLetterProvider:
    provider = os.getenv("LLM_PROVIDER", "mock").strip().lower()
    if provider == "bedrock":
        return BedrockCoverLetterProvider()
    if provider == "gemini":
        return GeminiCoverLetterProvider()
    return MockCoverLetterProvider()


cover_letter_provider = get_cover_letter_provider()
