from typing import Optional, Protocol


class StorageBackend(Protocol):
    """Abstract storage interface for all user data persistence."""

    # CV Versions
    async def list_versions(self, user_id: str) -> list[dict]: ...
    async def get_version(self, user_id: str, version_id: str) -> Optional[dict]: ...
    async def create_version(self, user_id: str, version_data: dict) -> dict: ...
    async def update_version(self, user_id: str, version_id: str, updates: dict) -> Optional[dict]: ...
    async def delete_version(self, user_id: str, version_id: str) -> bool: ...
    async def update_children_of_deleted_parent(self, user_id: str, parent_id: str) -> None: ...

    # User Profile
    async def get_profile(self, user_id: str) -> Optional[dict]: ...
    async def save_profile(self, user_id: str, profile: dict) -> None: ...
    async def delete_profile(self, user_id: str) -> bool: ...

    # Voice Profile
    async def get_voice_profile(self, user_id: str) -> Optional[dict]: ...
    async def save_voice_profile(self, user_id: str, profile: dict) -> None: ...
